toggle: true
alphabetize-plugin: true
column-view: true

css-file-name: CHANGE THIS VALUE
background-image-file-name: CHANGE THIS VALUE
plugins-pretext: This server uses the following plugins
server-pretext: This server runs

template-file-location: default
template-file-name: default

output-file-location: default
output-file-name: default
