toggle: true
alphabetize-plugin: true
column-view: true
last-updated: true
plugin-name-branding: true
background-image-file-name: CHANGE THIS VALUE
css-file-name: CHANGE THIS VALUE
output-file-name: default
output-file-location: default
plugins-pretext: This server uses the following plugins
server-pretext: This server runs
template-file-name: default
template-file-location: default
