name: PluginsManager
main: com.fawong.PluginsManager.PluginsManager
version: 11.09.20
website: http://fawong.com/
author: FAWONG
description: Various plugin and server related additions
commands:
  lp:
    description: Lists plugins in several different formats
    usage: |
           /<command> <display type>
           Example: /<command> row
           Example: /<command> column
  listplugins:
    aliases: [lp]
    description: alias for /<command>
    usage: /<command>
  pluginsmanager:
    aliases: [pmgr]
    description: manage plugins
    usage: /<command>
  pmgr:
    description: alias for /<command>
    usage: /<command>
permissions:
    pluginsmanager.*:
        description: Gives access to all pluginsmanager commands
        children:
            pluginsmanager.enable: true
